# Generated by Django 3.0.3 on 2020-02-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='article title')),
                ('description', models.TextField(max_length=9000, verbose_name='article title')),
                ('image', models.CharField(max_length=200, verbose_name='image')),
                ('link', models.CharField(max_length=200, verbose_name='link')),
                ('date', models.CharField(max_length=200, verbose_name='date')),
            ],
        ),
    ]
